compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard
  - code: YN0013
    level: discard

nmHoistingLimits: none

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs
